Layout/FirstHashElementIndentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Severity: warning

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Severity: warning

Naming/MemoizedInstanceVariableName:
  Severity: warning

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RescueStandardError:
  Enabled: false